use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename = "PlayerLastMatch")]
pub struct PlayerLastMatch {
    pub country: String,
    pub last_match: LastMatch,
    pub name: String,
    pub profile_id: i64,
    pub steam_id: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LastMatch {
    pub average_rating: Option<::serde_json::Value>,
    pub cheats: bool,
    pub ending_age: i64,
    pub expansion: Option<::serde_json::Value>,
    pub finished: i64,
    pub full_tech_tree: bool,
    pub game_type: i64,
    pub has_custom_content: Option<::serde_json::Value>,
    pub has_password: bool,
    pub leaderboard_id: i64,
    pub lobby_id: Option<::serde_json::Value>,
    pub lock_speed: bool,
    pub lock_teams: bool,
    pub map_size: i64,
    pub map_type: i64,
    pub match_id: String,
    pub match_uuid: String,
    pub name: String,
    pub num_players: i64,
    pub num_slots: i64,
    pub opened: i64,
    pub players: Players,
    pub pop: i64,
    pub ranked: bool,
    pub rating_type: i64,
    pub resources: i64,
    pub rms: Option<::serde_json::Value>,
    pub scenario: Option<::serde_json::Value>,
    pub server: String,
    pub shared_exploration: bool,
    pub speed: i64,
    pub started: i64,
    pub starting_age: i64,
    pub team_positions: bool,
    pub team_together: bool,
    pub treaty_length: i64,
    pub turbo: bool,
    pub version: String,
    pub victory: i64,
    pub victory_time: i64,
    pub visibility: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Players {
    pub civ: i64,
    pub clan: Option<::serde_json::Value>,
    pub color: i64,
    pub country: Option<::serde_json::Value>,
    pub drops: Option<::serde_json::Value>,
    pub games: Option<::serde_json::Value>,
    pub name: String,
    pub profile_id: i64,
    pub rating: i64,
    pub rating_change: Option<::serde_json::Value>,
    pub slot: i64,
    pub slot_type: i64,
    pub steam_id: String,
    pub streak: Option<::serde_json::Value>,
    pub team: i64,
    pub wins: Option<::serde_json::Value>,
    pub won: bool,
}

// #[test]
// fn ensure_player_last_match_roundtrips() {
//     let t = <PlayerLastMatch>::default();
//     let j = serde_json::to_string(&t).unwrap();
//     let r: PlayerLastMatch = serde_json::from_str(&j).unwrap();
//     assert_eq!(t, r);
// }

#[test]
fn ensure_player_last_match_from_sample() {
    let sample = r#"
{
   "profile_id":196240,
   "steam_id":"76561197984749679",
   "name":"GL.TheViper",
   "country":"NO",
   "last_match":{
      "match_id":"67645178",
      "lobby_id":null,
      "match_uuid":"c63271e4-5679-9c4a-b4fd-be498d3ddab6",
      "version":"44834",
      "name":"TG",
      "num_players":8,
      "num_slots":8,
      "average_rating":null,
      "cheats":false,
      "full_tech_tree":false,
      "ending_age":0,
      "expansion":null,
      "game_type":0,
      "has_custom_content":null,
      "has_password":true,
      "lock_speed":true,
      "lock_teams":true,
      "map_size":4,
      "map_type":9,
      "pop":200,
      "ranked":false,
      "leaderboard_id":0,
      "rating_type":0,
      "resources":0,
      "rms":null,
      "scenario":null,
      "server":"westindia",
      "shared_exploration":false,
      "speed":2,
      "starting_age":0,
      "team_together":true,
      "team_positions":false,
      "treaty_length":0,
      "turbo":false,
      "victory":9,
      "victory_time":1,
      "visibility":0,
      "opened":1612285928,
      "started":1612285928,
      "finished":1612288145,
      "players":[
         {
            "profile_id":197964,
            "steam_id":"76561198179087382",
            "name":"_WWP_Yo",
            "clan":null,
            "country":null,
            "slot":1,
            "slot_type":1,
            "rating":2753,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":2,
            "team":1,
            "civ":26,
            "won":false
         },
         {
            "profile_id":226575,
            "steam_id":"76561198313422112",
            "name":"_WWP_lyx",
            "clan":null,
            "country":null,
            "slot":2,
            "slot_type":1,
            "rating":2696,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":3,
            "team":1,
            "civ":32,
            "won":false
         },
         {
            "profile_id":208611,
            "steam_id":"76561198325239137",
            "name":"Villese",
            "clan":null,
            "country":null,
            "slot":3,
            "slot_type":1,
            "rating":2683,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":8,
            "team":4,
            "civ":27,
            "won":true
         },
         {
            "profile_id":215442,
            "steam_id":"76561198366260409",
            "name":"_WWP_Vivi",
            "clan":null,
            "country":null,
            "slot":4,
            "slot_type":1,
            "rating":2777,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":1,
            "team":1,
            "civ":4,
            "won":false
         },
         {
            "profile_id":210601,
            "steam_id":"76561198259118630",
            "name":"_WWP_Paladin",
            "clan":null,
            "country":null,
            "slot":5,
            "slot_type":1,
            "rating":2774,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":5,
            "team":1,
            "civ":22,
            "won":false
         },
         {
            "profile_id":265517,
            "steam_id":"76561198198305605",
            "name":"_WWP_Daniel",
            "clan":null,
            "country":null,
            "slot":6,
            "slot_type":1,
            "rating":2501,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":6,
            "team":4,
            "civ":1,
            "won":true
         },
         {
            "profile_id":431744,
            "steam_id":"76561198077768177",
            "name":"Rubenstock",
            "clan":null,
            "country":null,
            "slot":7,
            "slot_type":1,
            "rating":2632,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":7,
            "team":4,
            "civ":23,
            "won":true
         },
         {
            "profile_id":196240,
            "steam_id":"76561197984749679",
            "name":"GL.TheViper",
            "clan":null,
            "country":null,
            "slot":8,
            "slot_type":1,
            "rating":2555,
            "rating_change":null,
            "games":null,
            "wins":null,
            "streak":null,
            "drops":null,
            "color":4,
            "team":4,
            "civ":10,
            "won":true
         }
      ]
   }
}
    "#;

    let _: PlayerLastMatch = serde_json::from_str(&sample).unwrap();
}
