[package]
name = "transparencies-backend-rs"
publish = false
version = "0.0.1"
authors = ["the transparencies authors"]
edition = "2018"
repository = "https://github.com/transparencies/transparencies-backend-rs"
documentation = ""
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = [""]
categories = [""]
description = """
A foundation for building dynamic stream overlays written in Rust
"""
[package.metadata.release]
upload-doc = true
no-dev-version = true
pre-release-commit-message = "Release {{crate_name}} {{version}} / {{date}}"

[lib]
path = "src/lib.rs"

[[bin]]
name = "transparencies-backend-rs"      # The name of the target.
path = "src/main.rs"                    # The source file of the target.
test = true                             # Is tested by default.
doctest = true                          # Documentation examples are tested by default.
bench = true                            # Is benchmarked by default.
doc = true                              # Is documented by default.
harness = true                          # Use libtest harness.
edition = "2018"                        # The edition of the target.
#required-features = []                 # Features required to build this target (N/A for lib).

[dependencies]
# Error handling
human-panic = "1.0.3"
eyre = "0.6.5"
stable-eyre = "0.2.2"

# Logging
log = "0.4.14"
simple-log = "1.0.1"

# CLI
structopt = "0.3.21"

# Configuration
config = "0.10.1"
# config_struct = "0.5"
# ron = "0.6"

# HTTP
reqwest = { version = "0.11.1", features = ["json", "rustls-tls"] }
warp = "0.3.0"
hyper = "0.14.4"

# async
tokio = { version = "1.2.0", features = ["full"] }
futures = "0.3.12"

# De-/Serialisation
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.17"
#serde_any = { git = "https://github.com/simonsan/serde_any.git", version = "0.5.1", default-features = false, features = ["yaml", "toml", "json"]}
serde-aux = "2.1.1"
bytes = "1.0.1"

# Templating
# askama = "0.10"

# OpenAPI
openapi_utils = "0.2.0"
openapiv3 = "0.3.2"

# Utility
derive_builder = "0.9.0"
itertools = "0.10.0"
strum = { version = "0.20.0", features = ["derive"] }

# Validation
#validators-derive = "0.22.3"
#validators = "0.22.3"

[dev-dependencies]
thiserror = "1.0.24"
assert_cmd = "1.0.3"
predicates = "1.0.7"
lazy_static = "1.4.0"
pretty_assertions = "0.6.1"

[profile.dev]
opt-level=0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level=3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
