# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"
# List of explictly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.7 short identifier (+ optional exception)].
allow = [
    "MIT",
    "AFL-1.1",
    "AFL-1.2",
    "AFL-2.0",
    "AFL-2.1",
    "AFL-3.0",
    "AGPL-3.0",
    "Apache-1.0",
    "Apache-1.1",
    "Apache-2.0",
    "APSL-2.0",
    "BitTorrent-1.1",
    "BSD-3-Clause",
    "BSD-3-Clause-Clear",
    "BSD-4-Clause",
    "BSL-1.0",
    "CDDL-1.0",
    "CECILL-2.0",
    "CECILL-B",
    "CECILL-C",
    "CPAL-1.0",
    "CPL-1.0",
    "ECL-2.0",
    "EFL-2.0",
    "EPL-1.0",
    "EPL-2.0",
    "EUDatagrid",
    "EUPL-1.1",
    "EUPL-1.2",
    "FSFAP",
    "FTL",
    "GFDL-1.1",
    "GFDL-1.2",
    "GFDL-1.3",
    "gnuplot",
    "GPL-2.0",
    "GPL-3.0",
    "HPND",
    "IJG",
    "ISC",
]
# List of explictly disallowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.7 short identifier (+ optional exception)].
deny = [
    #"Nokia",
]
# Lint level for licenses considered copyleft
copyleft = "allow"
# Blanket approval or denial for OSI-approved or FSF Free/Libre licenses
# * both - The license will be approved if it is both OSI-approved *AND* FSF
# * either - The license will be approved if it is either OSI-approved *OR* FSF
# * osi-only - The license will be approved if is OSI-approved *AND NOT* FSF
# * fsf-only - The license will be approved if is FSF *AND NOT* OSI-approved
# * neither - This predicate is ignored and the default lint level is used
allow-osi-fsf-free = "fsf-only"
