max_width = 80
version = "Two"
edition = "2021"
reorder_imports = true
combine_control_expr = false
blank_lines_upper_bound = 2
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = false
# Nightly
imports_granularity = "Crate"
# Stable
# merge_imports = true
normalize_comments = false
wrap_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
imports_layout = "Vertical"
fn_args_layout = "Vertical"
control_brace_style = "ClosingNextLine"
trailing_comma = "Always"
spaces_around_ranges = true
report_todo = "Never"
report_fixme = "Never"
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
# license_template_path = ""
indent_style = "Visual"
force_multiline_blocks = true
condense_wildcard_suffixes = true
